
//ENUM SERIA BASICAMENTE UMA CONSTANTE
export enum DiasDaSemana{
    //PRECISA SER ORDENADA OU ATRIBUI UM VALOR,PODE SER STRING ,DATA,O VALOR VAI SEGUIR AS ORDEMS!!!
    DOMINGO=0,
    SEGUNDA=1,
    TERCA=2,
    QUARTA=3,
    QUINTA=4,
    SEXTA=5,
    SABADO=6

}